setGeneric("getAlleleA", function(object, ...) standardGeneric("getAlleleA"))
setGeneric("getAlleleB", function(object, ...) standardGeneric("getAlleleB"))
setGeneric("getAnnotation", function(object, ...) standardGeneric("getAnnotation"))
setGeneric("getAttribute", function(object, attname, varname, ...) standardGeneric("getAttribute"))
setGeneric("getBAlleleFreq", function(object, ...) standardGeneric("getBAlleleFreq"))
setGeneric("getChromosome", function(object, ...) standardGeneric("getChromosome"))
setGeneric("getDimension", function(object, varname, ...) standardGeneric("getDimension"))
setGeneric("getDimensionNames", function(object, varname, ...) standardGeneric("getDimensionNames"))
setGeneric("getGenotype", function(object, ...) standardGeneric("getGenotype"))
setGeneric("getGenotypeSelection", function(object, ...) standardGeneric("getGenotypeSelection"))
setGeneric("getLogRRatio", function(object, ...) standardGeneric("getLogRRatio"))
setGeneric("getMetadata", function(object, ...) standardGeneric("getMetadata"))
setGeneric("getNodeDescription", function(object, varname, ...) standardGeneric("getNodeDescription"))
setGeneric("getPosition", function(object, ...) standardGeneric("getPosition"))
setGeneric("getQuality", function(object, ...) standardGeneric("getQuality"))
setGeneric("getQuery", function(object, statement, ...) standardGeneric("getQuery"))
setGeneric("getScanAnnotation", function(object, ...) standardGeneric("getScanAnnotation"))
setGeneric("getScanID", function(object, ...) standardGeneric("getScanID"))
setGeneric("getScanVariable", function(object, varname, ...) standardGeneric("getScanVariable"))
setGeneric("getScanVariableNames", function(object, ...) standardGeneric("getScanVariableNames"))
setGeneric("getSex", function(object, ...) standardGeneric("getSex"))
setGeneric("getSnpAnnotation", function(object, ...) standardGeneric("getSnpAnnotation"))
setGeneric("getSnpID", function(object, ...) standardGeneric("getSnpID"))
setGeneric("getSnpVariable", function(object, varname, ...) standardGeneric("getSnpVariable"))
setGeneric("getSnpVariableNames", function(object, ...) standardGeneric("getSnpVariableNames"))
setGeneric("getVariable", function(object, varname, ...) standardGeneric("getVariable"))
setGeneric("getVariableNames", function(object, ...) standardGeneric("getVariableNames"))
setGeneric("getX", function(object, ...) standardGeneric("getX"))
setGeneric("getY", function(object, ...) standardGeneric("getY"))

setGeneric("hasBAlleleFreq", function(object) standardGeneric("hasBAlleleFreq"))
setGeneric("hasCoordVariable", signature="object", function(object, varname) standardGeneric("hasCoordVariable"))
setGeneric("hasLogRRatio", function(object) standardGeneric("hasLogRRatio"))
setGeneric("hasQuality", function(object) standardGeneric("hasQuality"))
setGeneric("hasScanAnnotation", function(object) standardGeneric("hasScanAnnotation"))
setGeneric("hasScanVariable", signature="object", function(object, varname) standardGeneric("hasScanVariable"))
setGeneric("hasSex", function(object) standardGeneric("hasSex"))
setGeneric("hasSnpAnnotation", function(object) standardGeneric("hasSnpAnnotation"))
setGeneric("hasSnpVariable", signature="object", function(object, varname) standardGeneric("hasSnpVariable"))
setGeneric("hasVariable", signature="object", function(object, varname) standardGeneric("hasVariable"))
setGeneric("hasX", function(object) standardGeneric("hasX"))
setGeneric("hasY", function(object) standardGeneric("hasY"))

setGeneric("nscan", function(object) standardGeneric("nscan"))
setGeneric("nsnp", function(object) standardGeneric("nsnp"))

setGeneric("writeAnnotation", function(object, value, ...) standardGeneric("writeAnnotation"))
setGeneric("writeMetadata", function(object, value, ...) standardGeneric("writeMetadata"))

setGeneric("autosomeCode", function(object) standardGeneric("autosomeCode"))
setGeneric("XchromCode", function(object) standardGeneric("XchromCode"))
setGeneric("YchromCode", function(object) standardGeneric("YchromCode"))
setGeneric("XYchromCode", function(object) standardGeneric("XYchromCode"))
setGeneric("MchromCode", function(object) standardGeneric("MchromCode"))

